# Generated by Django 3.1.7 on 2021-05-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
