# Generated by Django 3.1.7 on 2021-05-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210501_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='job_discription',
            new_name='jobdiscription',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='job_no',
            new_name='jobno',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='job_title',
            new_name='jobtitle',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='post_date',
            new_name='postdate',
        ),
    ]
