# Generated by Django 3.1.7 on 2021-05-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210501_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='jobdiscription',
            new_name='job_discription',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='jobno',
            new_name='job_no',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='jobtitle',
            new_name='job_title',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='postdate',
            new_name='pos_tdate',
        ),
    ]
