# Generated by Django 3.1.7 on 2021-05-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20210501_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='job_no',
        ),
        migrations.AddField(
            model_name='jobs',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
