# Generated by Django 3.1.7 on 2021-05-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20210504_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_status',
            field=models.BooleanField(default=True),
        ),
    ]
