# Generated by Django 3.2.3 on 2021-05-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_interview_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='company',
            new_name='company_user_id',
        ),
    ]
