# Generated by Django 3.2.3 on 2021-05-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_rename_company_interview_company_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='applidejob_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
