# Generated by Django 3.2.4 on 2021-06-20 07:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0011_interviewquestions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterviewQuestions',
            new_name='InterviewQuestion',
        ),
    ]
