# Generated by Django 3.2.4 on 2021-06-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_rename_interviewquestions_interviewquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='applidejob_id',
        ),
    ]
