# Generated by Django 3.2.4 on 2021-06-20 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mymodel',
        ),
    ]
