# Generated by Django 3.2.4 on 2021-06-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='max_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='min_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='sent',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
