# Generated by Django 3.2.4 on 2021-06-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_delete_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='apply_date',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='schduele_time',
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='Angry',
            field=models.TextField(default='Angry', max_length=1000),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='Disgust',
            field=models.TextField(default='Disgust', max_length=1000),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='Fear',
            field=models.TextField(default='Fear', max_length=10000),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='Happy',
            field=models.TextField(default='Hapyy', max_length=10000),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='Neutral',
            field=models.TextField(default='Neutral', max_length=10000),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='Sad',
            field=models.TextField(default='Sad', max_length=10000),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='Surprise',
            field=models.TextField(default='Surprise', max_length=10000),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='sent',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
