# Generated by Django 3.2.4 on 2021-06-28 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20210629_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='schduele_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=''),
            preserve_default=False,
        ),
    ]
