# Generated by Django 3.2.4 on 2021-06-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20210620_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='max_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionbank',
            name='min_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
