# Generated by Django 3.2.4 on 2021-06-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_auto_20210625_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestion',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='min_score',
        ),
    ]
