# Generated by Django 3.1.7 on 2021-04-10 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vib', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extend',
            old_name='source_name',
            new_name='user_type',
        ),
    ]
