# Generated by Django 3.1.7 on 2021-04-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vib', '0002_auto_20210410_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='extend',
            name='company_name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
