# Generated by Django 3.1.5 on 2021-04-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vib', '0002_extenduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('when', models.DateTimeField()),
            ],
        ),
    ]
