# Generated by Django 3.1.5 on 2021-04-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vib', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
