# Generated by Django 3.2.3 on 2021-05-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vib', '0004_auto_20210411_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extend',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
